version: "3.7"
services:
  db:
    container_name: nfl-looser-pool-database
    image: postgres
    networks:
      new:
        aliases:
          - database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data 
      
  server:
    container_name: nfl-looser-pool-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - new
    ports:
    - "8080:8080"
volumes:
  data:
networks:
  new: