version: "3.7"
services:
  database:
  # need netwroks!!
    container_name: nfl-looser-pool-database
    image: postgres
    restart: always
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data 
  server:
    container_name: nfl-looser-pool-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data:
# networks:
#   ingress:
#     name: existing_docker_network
#     external: true